// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/xushiwei/rbspec"

const _ = true

type A struct {
	rbspec.RobotImpl
	*rbspec.RobotGame
}
type B struct {
	rbspec.SpriteImpl
	*Game
}
type Game struct {
	rbspec.Game
}

func (this *Game) MainEntry() {
}
func (this *Game) Main() {
	rbspec.Gopt_Game_Main(this, new(A), new(B))
}
func (this *A) Classfname() string {
	return "A"
}
func (this *A) Main() {
}
func (this *B) Classfname() string {
	return "B"
}
func (this *B) Main() {
}
func main() {
	new(Game).Main()
}
